#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
DISTRO_NAME=qpid-dispatch-image

mkdir --parents /etc/qpid-dispatch/

# unpack
{
    cd /tmp/artifacts
    mv $ADDED_DIR/run_qdr.sh $ADDED_DIR/qdrouterd.conf.template $ADDED_DIR/colocated-topic.snippet $ADDED_DIR/ssl.snippet $ADDED_DIR/subscriptions.snippet $ADDED_DIR/amqp-kafka-bridge.snippet /etc/qpid-dispatch/
    tar xzf "$DISTRO_NAME.tar.gz"
    cp -a usr /
    cp -a etc /
    rm -rf usr
    rm -rf etc
}