#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
#INCLUDED_SCRIPT_DIR=opt/${DISTRO_NAME}

#For volume
mkdir -p /var/run/artemis/
chown 185 /var/run/artemis

mkdir -p /home/jboss/
chown 185 /home/jboss

PATH=$ARTEMIS_HOME/bin:$PATH

# unpack apache-artemis
{
    cd /tmp/artifacts
    mv $DISTRO_NAME-bin.tar.gz /opt
    tar xf /opt/$DISTRO_NAME-bin.tar.gz
    mv $DISTRO_NAME /opt
}
# unpack artemis-image
{    
    tar xf "artemis-image.tar"
    mv config_templates /config_templates
    mv $ADDED_DIR/launch.sh /opt/$DISTRO_NAME/bin
    mv $ADDED_DIR/safe_launch.sh /opt/$DISTRO_NAME/bin
    mv $ADDED_DIR/partitionPV.sh /opt/$DISTRO_NAME/bin
    mv opt/$DISTRO_NAME/lib/artemis-amqp-connector.jar /opt/$DISTRO_NAME/lib
}
chown -R 185:0 /opt/$DISTRO_NAME
chmod -R a+rwX /home/jboss
chmod -R a+rwX /opt/$DISTRO_NAME
