#!/bin/sh

set -e

mkdir -p /opt/app-root/src/
# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tar.gz"
    mv *.js /opt/app-root/src
}
npm install -g debug && npm install -g rhea

#need to create home dir for community images
mkdir -p /home/jboss
chown 185 /home/jboss
chmod -R a+rwX /home/jboss
