#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

mkdir -p /opt/app-root/src/
mkdir -p /opt/ragent/bin
# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv *.js /opt/app-root/src

    mv $ADDED_DIR/launch.sh /opt/ragent/bin
}

#need to create home dir for community images
mkdir -p /home/jboss
chown 185 /home/jboss
chmod -R a+rwX /home/jboss
chmod -R a+rwX /opt/app-root/
