#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

DISTRO_NAME=topic-forwarder

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv "$DISTRO_NAME" /opt
    mv $ADDED_DIR/launch.sh /opt/$DISTRO_NAME/bin 
}
chown -R 185:0 /opt/topic-forwarder
chmod -R a+rwX $HOME
chmod -R a+rwX /opt/topic-forwarder