#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

mkdir -p /opt/app-root/src/
mkdir -p /opt/console/bin/

# unpack
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tgz"
    mv * /opt/app-root/src
    mv $ADDED_DIR/launch.sh /opt/console/bin
    
}

#need to create home dir for community images
mkdir -p /home/jboss
chown 185 /home/jboss
chmod -R a+rwX /home/jboss
chown -R 185 /opt/app-root/src
